site_name: DTX
site_description: Digital Technology Interactive Textbook
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.tabs.link
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Grade 9:
      - Unit 3:
          - Lesson 1: grade9/unit3/lesson1/index.md  # 각 폴더 안의 메인 md 파일 경로로 지정하세요
          - Lesson 2: grade9/unit3/lesson2/index.md
          - Lesson 3: grade9/unit3/lesson3/index.md
          - Lesson 4: grade9/unit3/lesson4/index.md
          - Lesson 5: grade9/unit3/lesson5/index.md
